runtime: python310 # or python39 if you're using Python 3.9
entrypoint: gunicorn -b :$PORT server:app

instance_class: F2 # You can change based on your needs

env_variables:
  MODEL_URL: 'https://storage.googleapis.com/ctrack-model/place_detection_model.h5'

handlers:
  - url: /.*
    script: auto
