services:
  - type: web
    name: ctrack-locator
    env: python
    buildCommand: pip install -r requirements.txt && python prepare_model.py
    startCommand: gunicorn --timeout 120 --workers 1 --threads 1 wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: TF_FORCE_GPU_ALLOW_GROWTH
        value: 'true'
      - key: TF_CPP_MIN_LOG_LEVEL
        value: '3'
    plan: free
    healthCheckPath: /health
